- hosts: web
  become: yes
  tasks:
    - name: edit index
      lineinfile:
        path: /var/www/html/index.html
        line: "I 'm back !!"
      when:
        - ansible_hostname == "ip-172-31-19-160"
