- hosts: web
  become: yes
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: latest
    - name: enable https
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Adding index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Add line to index
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello Akshay Virkhare"
      register: output
    - debug: msg="Register ouput is {{output}}"
    - name: Create tmp file
      file:
        path: /tmp/newfile
        state: touch
    - name: edit file
      lineinfile:
        path: /tmp/newfile
        line: "{{output}}"
- hosts: db
  become: yes
  tasks:
    - name: Installing mysql
      apt:
        name:
          - mysql-server-8.0
        state: latest
