- hosts: web
  become: yes
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      listen: "restart web"
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: latest
    - name: enable https
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Adding index file
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Add line to index
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello Akshay Virkhare"
    - name: chnage config
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: 'DocumentRoot /var/www/html'
        replace: 'DocumentRoot "/opt/www"'
        backup: yes
      notify: "restart web"
- hosts: db
  become: yes
  tasks:
    - name: Installing mysql
      apt:
        name:
          - mysql-server-8.0
        state: latest
