- hosts: web
  become: yes
  tasks:
    - name: Deploy app binary
      copy:
        src:
        dest:
      tags:
        - webdeploy
- hosts: db
  become: yes
  tasks:
    - name: deployy sql script
      copy:
        scr:
        dest:
      tags:
        - dbdeploy
