- hosts: patch
  become: yes
  tasks:
    - name: install apache
      dnf:
        name: httpd
        state: latest
    - name: enable https
      service:
        name: httpd
        state: started
        enabled: yes

