- name: Install and Configure BIND DNS
  hosts: dns_servers
  tasks:
    - name: Install bind9 package
      ansible.builtin.apt:
        name: bind9
        state: present
      become: true
    - name: Configure named.conf.options
      ansible.builtin.template:
        src: named.conf.options.j2
        dest: /etc/bind/named.conf.options
      register: named_conf_change
      become: true
    - name: Deploy zone files using Jinja2 templates
      ansible.builtin.template:
        src: zone.j2
        dest: /etc/bind/{{ item.domain }}.zone
      loop: "{{ domains }}"
      vars:
        domain_data: "{{ item }}"
        nameserver_ip: "{{ ansible_host }}"
      register: zone_file_change
      become: true
    - name: Reload zone files
      ansible.builtin.shell: rndc reload
      when: zone_file_change.changed
      become: true
    - name: Restart BIND DNS server
      ansible.builtin.service:
        name: bind9
        state: restarted
      when: named_conf_change.changed
      become: true
