---
- name: Install Nginx Web Server
  ansible.builtin.package:
    name: nginx

- name: allow HTTP traffic via firewalld
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Copy directory recursively to target node
  ansible.builtin.copy:
    src: ../html/
    dest: /usr/share/nginx/html/
    mode: 0644
    directory_mode: 0755
